import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Art&Craft Eshop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto p-2 max-w-full md:max-w-7xl">
          <Navbar />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
